### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/ServiceManagement#11]
this app is a must to assist development by incrementally testing the integration of components when they are updated

needs https://github.com/mF2C/mF2C/issues/80

**Comment by cjdcordeiro** [comment]
need INTEL's feedback

**Comment by cjdcordeiro** [comment]
@giulianacarullo (up) @aleckey

**Comment by fcarp10** [comment]
Testing Hello-world workflow for IT-2 docker compose file. This is based on my tests, if you think your module is working, for IT-2 services, please contact me. We should try to include the maximum number of modules for this test. 

Working AND participating:
- traefik
- cimi (+rc)
- slalite
- service-manager
- lm-um
- dataclay (dcproxy + ds1java1 + logicmodule1)

Working, but NOT participating:
- eventService 
- compss (preparing hello world app)

NOT working:
- discovery
- policies
- resouce-categorization
- identification
- cau-client
- analytics_engine + snap + influxdb + snaptemp + neo4j + landscaper + web

**Comment by fcarp10** [comment]
depends on #102 #103 #104 #105 #106 #107 #108
