### ISSUE TITLE
Service definition

### ISSUE THREAD

**Issue by fcarp10** [mF2C/ServiceManagement#12]
Update on the definition of a service

**Comment by cjdcordeiro** [comment]
@FranCarpio can you write the final definition here?

**Comment by fcarp10** [comment]
It is probably not final... but for the time being...

{
    "name": "hello-world",
    "description": "Hello World Service",
    "exec": "hello-world",
    "exec_type": "docker",
    "exec_ports": [8080],
    "cpu_arch": "arm",
    "os": "linux", 
    "memory_min": 1000,
    "storage_min": 100, 
    "disk": 100, 
    "agent_type": "cloud",
    "req_resource": ["Location", "Sentinel", "Ambulance"],
    "opt_resource": ["SenseHat", "GP-20U7"],
    "category": 3 
}
