### ISSUE TITLE
Add Qos Model to Dataclay

### ISSUE THREAD

**Issue by fcarp10** [mF2C/ServiceManagement#20]
Java class as reference for the qosmodel resource in dataclay:

https://github.com/mF2C/ServiceManagement/blob/master/src/main/java/sm/elements/QosModel.java

**Comment by daniwhere** [comment]
Implemented in PR https://github.com/mF2C/mF2C/pull/141 . Working json example: 


{
    "id": "qos-model/qos-model",
    "service": { "href": "service/service" },
    "agreement": { "href": "agreement/agreement" } ,
    "agents": [ { "href": "agent/agent" } ],
    "config": "qos config",
    "num_service_instances": 2,
    "num_service_failures": 3,
    "current_state": [1.0, 3.5],
    "next_state": [1.0]
    
  }

@fcarp10 Please confirm, everything is OK!
