### ISSUE TITLE
Define workflow for QoS enforcement

### ISSUE THREAD

**Issue by fcarp10** [mF2C/ServiceManagement#21]
1. LM gets a list of agents from Recomender
2. LM sends the list to COMPSs
3. COMPSs publish expected execution time during service runtime
4. QoS enforcer detects if SLA will be broken based on the expected execution time 
5. if true, then QoS enforcer notifies the LM (how??)
6. LM gets an updated (if so) list of devices from Recommender
7. LM sents the new list to COMPSs

**Comment by rsucasas** [comment]
In `2.` and `7.`, LM will use service's `num_agents` property to set the number agents where to run the COMPSs service.

In `5.`, LM will provide a method to get and process the QoS enforcer notifications
